# Docker Compose file version (use a recent stable version)
version: '3.8'

# Define the services (containers)
services:
  # Name of your service (can be anything descriptive)
  mcp-server:
    # Specify the image to use, pointing to your GHCR repository
    image: ghcr.io/laomeifun/mcp-streamable-http-example:latest
    environment:
      # Set the environment variable for the server URL
      - MCP_SERVER_URL=http://localhost:3000
    # Set a restart policy to automatically restart the container if it stops
    # 'unless-stopped' means it restarts unless manually stopped
    restart: unless-stopped
    # Optional: Define a container name for easier reference
    container_name: mcp_streamable_server_compose
